# Generated by Django 4.1.3 on 2023-10-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ash_store', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
