# Generated by Django 4.1.3 on 2023-10-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ash_store', '0005_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=50),
        ),
    ]
